// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as manifest$0 from "../manifest/models.js";

/**
 * Dependency is one declared dependency link, as authored. It is reported,
 * never evaluated: whether the target exists or is new enough is the Health
 * phase's question.
 */
export interface Dependency {
    "uniqueID": string;
    "minimumVersion": string;
    "isRequired": boolean;
}

/**
 * DuplicateEntry is one unit among those claiming a duplicate Unique ID.
 */
export interface DuplicateEntry {
    "path": string;
    "version": string;
}

/**
 * DuplicateGroup is one Unique ID claimed by more than one unit. SMAPI loads
 * both copies under one identity, so the product treats the group as a launch
 * blocker: after launch the two copies cannot be told apart.
 */
export interface DuplicateGroup {
    "uniqueID": string;
    "entries": DuplicateEntry[] | null;
    "launchBlocker": boolean;
}

/**
 * FieldError is one diagnosed manifest problem, mapped from the parser's own
 * error so the preview never re-states a message.
 */
export interface FieldError {
    "field": string;
    "stage": manifest$0.Stage;
    "message": string;
}

/**
 * Finding is one thing the preview reports about the staged tree that is not a
 * Mod Unit.
 */
export interface Finding {
    "kind": FindingKind;
    "path": string;
    "message": string;
}

/**
 * FindingKind is what one layout finding is about.
 */
export enum FindingKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * FindingLegacyXnb is legacy packed content that can never be a Mod Unit.
     * The per-folder finding carries the scanner's explanation; the
     * package-level finding carries PRD §16's copy verbatim.
     */
    FindingLegacyXnb = "legacy-xnb",

    /**
     * FindingRootContentTree is a top-level Content directory of packed
     * content: game-folder content, not a mod.
     */
    FindingRootContentTree = "root-content-tree",

    /**
     * FindingSMAPIInstaller is the SMAPI installer bundle a user unzipped into
     * the package by mistake.
     */
    FindingSMAPIInstaller = "smapi-installer",

    /**
     * FindingSMAPIPayload is the extracted installer's own payload directory.
     */
    FindingSMAPIPayload = "smapi-payload",

    /**
     * FindingHiddenManifests is a manifest buried below a folder SMAPI reads
     * as manifest-less, the shape a poisoned organizer makes.
     */
    FindingHiddenManifests = "hidden-manifests",

    /**
     * FindingEmptyFolder is a folder with nothing SMAPI considers.
     */
    FindingEmptyFolder = "empty-folder",

    /**
     * FindingIgnoredFolder is a folder SMAPI skips by convention: a dot-prefixed
     * name, or a folder that links back to one already scanned.
     */
    FindingIgnoredFolder = "ignored-folder",

    /**
     * FindingVortexLeftover is a folder another manager left behind holding
     * only its marker.
     */
    FindingVortexLeftover = "vortex-leftover",

    /**
     * FindingLooseRootFiles is mod-looking files directly in the stage root,
     * which SMAPI never treats as a mod.
     */
    FindingLooseRootFiles = "loose-root-files",

    /**
     * FindingUnreadable is a folder or manifest the filesystem refused to read.
     */
    FindingUnreadable = "unreadable",

    /**
     * FindingScanLimit is where the scan's work bound ran out: everything below
     * it is unknown, so the package cannot be judged complete.
     */
    FindingScanLimit = "scan-limit",
};

/**
 * Kind is what a staged folder is, as the preview shows it.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindCodeMod is a Mod Unit SMAPI loads directly.
     */
    KindCodeMod = "code-mod",

    /**
     * KindContentPack is a Mod Unit consumed by its host mod.
     */
    KindContentPack = "content-pack",

    /**
     * KindInvalid is a folder whose manifest failed validation: it keeps
     * everything the author wrote, but it is not loadable.
     */
    KindInvalid = "invalid",
};

/**
 * Unit is one Mod Unit the staged package holds, with everything the preview
 * and the confirmation step show about it.
 */
export interface Unit {
    /**
     * RelativePath is the unit's folder relative to the stage root,
     * slash-separated. "" is the stage root itself, which happens when the
     * package's own manifest.json sits at its top level (PRD §15 Example B).
     */
    "relativePath": string;

    /**
     * FolderName is the folder's name — path.Base(RelativePath) — or, for a
     * root manifest, the manifest's Name, since the folder that will hold the
     * installed unit takes its name from the manifest.
     */
    "folderName": string;

    /**
     * Name, Author, Version and UniqueID are the manifest's identity as
     * authored; an invalid manifest keeps them rather than dropping them.
     */
    "name": string;
    "author": string;
    "version": string;
    "uniqueID": string;

    /**
     * Kind is the unit's type, or KindInvalid when its manifest failed.
     */
    "kind": Kind;

    /**
     * EntryDll is the code mod's entry assembly, "" for a content pack.
     */
    "entryDll": string;

    /**
     * ContentPackFor is the host Unique ID a content pack declares, "" for a
     * code mod.
     */
    "contentPackFor": string;

    /**
     * Dependencies are the declared dependency links, in manifest order.
     */
    "dependencies": Dependency[] | null;

    /**
     * Verdict is the manifest parser's judgment.
     */
    "verdict": manifest$0.Verdict;

    /**
     * FieldErrors are the parser's per-field diagnoses, in parser order.
     */
    "fieldErrors": FieldError[] | null;

    /**
     * SystemMod reports whether the Unique ID names one of SMAPI's bundled
     * Mod Units.
     */
    "systemMod": boolean;

    /**
     * Installable reports whether this unit itself can be installed: its
     * verdict parsed and its kind is a loadable one.
     */
    "installable": boolean;

    /**
     * Note explains a unit that is not installable; "" otherwise.
     */
    "note": string;
}
