// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApplicationService reports the identity of the application it was constructed
 * for. It is bound to the frontend as ApplicationService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Info returns the application's identity.
 */
export function Info(): $CancellablePromise<$models.Info> {
    return $Call.ByID(1279469806);
}

/**
 * ProbeFailure is a failing demo probe for the typed-error path. It returns a
 * zero Info and a PROBE_FAILURE *apperror.AppError; Wails serialises the error
 * through the service's MarshalError hook (apperror.MarshalError) so the
 * TypeScript call rejects with the structured error as its cause.
 */
export function ProbeFailure(): $CancellablePromise<$models.Info> {
    return $Call.ByID(2863300802);
}
