// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inspect$0 from "../inspect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tasks$0 from "../tasks/models.js";

/**
 * DetectNowResult is one automatic discovery pass: the upserted installs,
 * whether the pointer outcome needs an explicit choice, and the sentence
 * the frontend renders. PointerOutcome reuses the settled vocabulary:
 * adopted-vacuum (no pointer before), adopted-stale (dangling pointer
 * repaired), kept-healthy (a healthy pointer survives), needs-choice (many
 * finds leave the pointer for the per-row choosers). No new error codes.
 */
export interface DetectNowResult {
    "found": GameInstallView[] | null;
    "adopted": GameInstallView | null;
    "pointerOutcome": string;
    "needsChoice": boolean;
    "message": string;
    "installsKnown": number;
}

/**
 * EventSink receives task event hints. *application.EventManager satisfies
 * it, and a nil sink (tests, headless runs) is valid by design: every
 * emission is best-effort and no correctness path depends on one (ADR 0006).
 */
export type EventSink = any;

/**
 * GameInstallView is one game_installs row plus its primary marker. Nullable
 * columns arrive as nil: null means present-but-unknown (versions) or
 * not-yet-detected/absent (entry point), never guessed.
 */
export interface GameInstallView {
    "id": number;
    "path": string;
    "source": string;
    "smapiExePath": string | null;
    "gameVersion": string | null;
    "smapiVersion": string | null;
    "smapiState": string;
    "isPrimary": boolean;
}

/**
 * HealthDatabase is the live database state read through the open handle. A
 * nil handle reports State "unavailable: ..." with Healthy false — never
 * fabricated as healthy.
 */
export interface HealthDatabase {
    "path": string;
    "version": number;
    "healthy": boolean;
    "state": string;
}

/**
 * HealthDirectory is one product directory and whether Astradew can write to
 * it right now.
 */
export interface HealthDirectory {
    "name": string;
    "path": string;
    "writable": boolean;
}

/**
 * HealthFinding is one observed problem: what was seen, why it matters, and
 * what the player can do about it.
 */
export interface HealthFinding {
    "severity": string;
    "what": string;
    "why": string;
    "action": string;
}

/**
 * HealthGameSection is the observed primary Game Installation. Null on the
 * wire until the primary pointer resolves to a row: path and source name
 * the install, installsKnown counts game_installs rows, and a null
 * gameVersion means the game is present but its version is unknown — never
 * guessed.
 */
export interface HealthGameSection {
    "path": string;
    "source": string;
    "gameVersion": string | null;
    "installsKnown": number;
}

/**
 * HealthReport is everything the Health view can honestly report. The JSON
 * keys are the contract the frontend binds to.
 */
export interface HealthReport {
    "name": string;
    "version": string;
    "dataRoot": string;
    "directories": HealthDirectory[] | null;
    "database": HealthDatabase;
    "initialisation": InitStep[] | null;
    "findings": HealthFinding[] | null;
    "unavailable": HealthUnavailable[] | null;
    "game": HealthGameSection | null;
    "smapi": HealthSmapiSection | null;
}

/**
 * HealthSmapiSection is the observed SMAPI state inside the primary Game
 * Installation. Null until a game is observed (SMAPI is unobservable
 * without a game dir); an absent SMAPI is an observed state, never null.
 * State repeats the detect.SmapiStatus vocabulary verbatim
 * (absent|complete|partial). A null version means unknown — or conflicted,
 * which trusts none of its sources and stores nothing. Detail is one honest
 * sentence (missing list, conflict sources, last-run-only caveat). Missing
 * names the absent signals when partial, else empty, never null.
 */
export interface HealthSmapiSection {
    "state": string;
    "version": string | null;
    "detail": string;
    "missing": string[] | null;
}

/**
 * HealthUnavailable is one capability the backend cannot offer yet. Anything
 * unobservable lands here, never as a pass.
 */
export interface HealthUnavailable {
    "name": string;
    "status": string;
    "reason": string;
}

/**
 * Info is the identity of the running application as the interface sees it.
 */
export interface Info {
    "name": string;
    "version": string;
}

/**
 * InitStep is one startup step and whether it completed. Only steps that ran
 * are recorded; a step that did not run is absent, never marked ok.
 */
export interface InitStep {
    "name": string;
    "ok": boolean;
    "message": string;
}

/**
 * InspectionFailure is the typed failure of one inspection. Code is the
 * apperror code the row's outcome carries; Message is its stable sentence
 * and Details names the offending entry, path, or reason.
 */
export interface InspectionFailure {
    "code": string;
    "message": string;
    "details": string;
}

/**
 * InspectionView is the live state of one inspection: the durable row, the
 * view status, the preview when it succeeded, and the failure when it
 * failed. Both payload fields are nil unless their status applies.
 */
export interface InspectionView {
    "task": tasks$0.Task;
    "status": string;
    "preview": Preview | null;
    "failure": InspectionFailure | null;
}

/**
 * Preview is the wire form of one finished inspection: the archive's
 * identity, its digests, and everything internal/inspect derived from the
 * staged tree. The embedded inspect.Preview inlines its own JSON keys
 * (units, findings, duplicates, installable).
 */
export interface Preview {
    "sourcePath": string;
    "originalName": string;
    "sizeBytes": number;
    "archiveSha256": string;
    "packageSha256": string;

    /**
     * Units are the Mod Units found, the stage root's own unit first when the
     * package has one, then the scanner's units in scan order.
     */
    "units": inspect$0.Unit[] | null;

    /**
     * Findings are the layout findings, record-derived ones in scan order
     * first, then the root pass's own, then the package-level XNB mark last.
     */
    "findings": inspect$0.Finding[] | null;

    /**
     * Duplicates are the multi-entry Unique ID groups only.
     */
    "duplicates": inspect$0.DuplicateGroup[] | null;

    /**
     * Installable reports whether Astradew can offer to install the package:
     * at least one installable unit, and no scan-limit finding.
     */
    "installable": boolean;
}

/**
 * SettingView is one registry setting with its current value: what the
 * /settings view renders per row. Value holds a JSON scalar (string, bool,
 * or number); IsDefault reports whether it equals the declared default.
 */
export interface SettingView {
    "name": string;
    "kind": string;
    "value": any;
    "isDefault": boolean;
    "description": string;
}
