// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DetectNowResult is one automatic discovery pass: the upserted installs,
 * whether the pointer outcome needs an explicit choice, and the sentence
 * the frontend renders. PointerOutcome reuses the settled vocabulary:
 * adopted-vacuum (no pointer before), adopted-stale (dangling pointer
 * repaired), kept-healthy (a healthy pointer survives), needs-choice (many
 * finds leave the pointer for the per-row choosers). No new error codes.
 */
export interface DetectNowResult {
    "found": GameInstallView[] | null;
    "adopted": GameInstallView | null;
    "pointerOutcome": string;
    "needsChoice": boolean;
    "message": string;
    "installsKnown": number;
}

/**
 * GameInstallView is one game_installs row plus its primary marker. Nullable
 * columns arrive as nil: null means present-but-unknown (versions) or
 * not-yet-detected/absent (entry point), never guessed.
 */
export interface GameInstallView {
    "id": number;
    "path": string;
    "source": string;
    "smapiExePath": string | null;
    "gameVersion": string | null;
    "smapiVersion": string | null;
    "smapiState": string;
    "isPrimary": boolean;
}

/**
 * HealthDatabase is the live database state read through the open handle. A
 * nil handle reports State "unavailable: ..." with Healthy false — never
 * fabricated as healthy.
 */
export interface HealthDatabase {
    "path": string;
    "version": number;
    "healthy": boolean;
    "state": string;
}

/**
 * HealthDirectory is one product directory and whether Astradew can write to
 * it right now.
 */
export interface HealthDirectory {
    "name": string;
    "path": string;
    "writable": boolean;
}

/**
 * HealthFinding is one observed problem: what was seen, why it matters, and
 * what the player can do about it.
 */
export interface HealthFinding {
    "severity": string;
    "what": string;
    "why": string;
    "action": string;
}

/**
 * HealthGameSection is the observed primary Game Installation. Null on the
 * wire until the primary pointer resolves to a row: path and source name
 * the install, installsKnown counts game_installs rows, and a null
 * gameVersion means the game is present but its version is unknown — never
 * guessed.
 */
export interface HealthGameSection {
    "path": string;
    "source": string;
    "gameVersion": string | null;
    "installsKnown": number;
}

/**
 * HealthReport is everything the Health view can honestly report. The JSON
 * keys are the contract the frontend binds to.
 */
export interface HealthReport {
    "name": string;
    "version": string;
    "dataRoot": string;
    "directories": HealthDirectory[] | null;
    "database": HealthDatabase;
    "initialisation": InitStep[] | null;
    "findings": HealthFinding[] | null;
    "unavailable": HealthUnavailable[] | null;
    "game": HealthGameSection | null;
    "smapi": HealthSmapiSection | null;
}

/**
 * HealthSmapiSection is the observed SMAPI state inside the primary Game
 * Installation. Null until a game is observed (SMAPI is unobservable
 * without a game dir); an absent SMAPI is an observed state, never null.
 * State repeats the detect.SmapiStatus vocabulary verbatim
 * (absent|complete|partial). A null version means unknown — or conflicted,
 * which trusts none of its sources and stores nothing. Detail is one honest
 * sentence (missing list, conflict sources, last-run-only caveat). Missing
 * names the absent signals when partial, else empty, never null.
 */
export interface HealthSmapiSection {
    "state": string;
    "version": string | null;
    "detail": string;
    "missing": string[] | null;
}

/**
 * HealthUnavailable is one capability the backend cannot offer yet. Anything
 * unobservable lands here, never as a pass.
 */
export interface HealthUnavailable {
    "name": string;
    "status": string;
    "reason": string;
}

/**
 * Info is the identity of the running application as the interface sees it.
 */
export interface Info {
    "name": string;
    "version": string;
}

/**
 * InitStep is one startup step and whether it completed. Only steps that ran
 * are recorded; a step that did not run is absent, never marked ok.
 */
export interface InitStep {
    "name": string;
    "ok": boolean;
    "message": string;
}

/**
 * SettingView is one registry setting with its current value: what the
 * /settings view renders per row. Value holds a JSON scalar (string, bool,
 * or number); IsDefault reports whether it equals the declared default.
 */
export interface SettingView {
    "name": string;
    "kind": string;
    "value": any;
    "isDefault": boolean;
    "description": string;
}
