// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HealthDatabase is the live database state read through the open handle. A
 * nil handle reports State "unavailable: ..." with Healthy false — never
 * fabricated as healthy.
 */
export interface HealthDatabase {
    "path": string;
    "version": number;
    "healthy": boolean;
    "state": string;
}

/**
 * HealthDirectory is one product directory and whether Astradew can write to
 * it right now.
 */
export interface HealthDirectory {
    "name": string;
    "path": string;
    "writable": boolean;
}

/**
 * HealthFinding is one observed problem: what was seen, why it matters, and
 * what the player can do about it.
 */
export interface HealthFinding {
    "severity": string;
    "what": string;
    "why": string;
    "action": string;
}

/**
 * HealthReport is everything the Health view can honestly report. The JSON
 * keys are the contract the frontend binds to.
 */
export interface HealthReport {
    "name": string;
    "version": string;
    "dataRoot": string;
    "directories": HealthDirectory[] | null;
    "database": HealthDatabase;
    "initialisation": InitStep[] | null;
    "findings": HealthFinding[] | null;
    "unavailable": HealthUnavailable[] | null;
}

/**
 * HealthUnavailable is one capability the backend cannot offer yet. Anything
 * unobservable lands here, never as a pass.
 */
export interface HealthUnavailable {
    "name": string;
    "status": string;
    "reason": string;
}

/**
 * Info is the identity of the running application as the interface sees it.
 */
export interface Info {
    "name": string;
    "version": string;
}

/**
 * InitStep is one startup step and whether it completed. Only steps that ran
 * are recorded; a step that did not run is absent, never marked ok.
 */
export interface InitStep {
    "name": string;
    "ok": boolean;
    "message": string;
}

/**
 * SettingView is one registry setting with its current value: what the
 * /settings view renders per row. Value holds a JSON scalar (string, bool,
 * or number); IsDefault reports whether it equals the declared default.
 */
export interface SettingView {
    "name": string;
    "kind": string;
    "value": any;
    "isDefault": boolean;
    "description": string;
}
