// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Stage is which parsing stage produced a FieldError.
 */
export enum Stage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StageSyntax means the file is not a JSON object at all.
     */
    StageSyntax = "syntax",

    /**
     * StageInterpretation means a present value has the wrong shape.
     */
    StageInterpretation = "interpretation",

    /**
     * StageValidation means the interpreted values fail identity rules, or
     * deviate from the published manifest schema. Schema deviations are
     * warnings: they degrade the verdict to partial without dropping the unit.
     */
    StageValidation = "validation",
};

/**
 * Verdict is the parser's judgment of one manifest.
 */
export enum Verdict {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * VerdictValid means every field parsed and validated.
     */
    VerdictValid = "valid",

    /**
     * VerdictPartial means required identity holds but an optional field
     * is malformed; the unit survives with warnings.
     */
    VerdictPartial = "partial",

    /**
     * VerdictInvalid means the file is not JSON, a value cannot be
     * interpreted at all, or required identity is missing or malformed.
     */
    VerdictInvalid = "invalid",
};
