// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status is the lifecycle state of a Task record.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StatusPending marks a record that was created but never progressed.
     */
    StatusPending = "pending",

    /**
     * StatusRunning marks a record with reported progress that has not
     * finished yet.
     */
    StatusRunning = "running",

    /**
     * StatusSucceeded marks a finished record carrying a result summary
     * in outcome.
     */
    StatusSucceeded = "succeeded",

    /**
     * StatusFailed marks a finished record carrying the apperror code in
     * outcome.
     */
    StatusFailed = "failed",
};

/**
 * Task is one durable operation record. The JSON keys are the contract
 * the frontend binds to. Outcome is nil until the task finishes: then it
 * holds the result summary (succeeded) or the apperror code (failed).
 */
export interface Task {
    "id": string;
    "operation": string;
    "status": Status;
    "current": number;
    "total": number;
    "message": string;
    "outcome": string | null;
    "createdAt": string;
    "updatedAt": string;
}
