// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Paths is the resolved application data layout. The JSON keys are the
 * contract the frontend binds to.
 */
export interface Paths {
    "root": string;
    "database": string;
    "library": string;
    "profiles": string;
    "backups": string;
    "cache": string;
    "logs": string;
    "temp": string;
}
